version: '2'
services:
    ella_finance-app:
        image: ella_finance
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://ella_finance-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ella_finance
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ella_finance-mongodb:
        extends:
            file: mongodb.yml
            service: ella_finance-mongodb
