version: '2'
services:
    ella_finance-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/ella_finance/mongodb/:/data/db/
